version: "3"

services:
  database:
    image: postgres:9.6.20-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build:
      context: https://corentin-grard:DU1sMNVe9xssxyeKjYsY@gitlab.mines-ales.fr/infres-11-projet-3a/gesco/backend.git
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:admin@database:5432/db?serverVersion=5.7
      - POSTGRES_PASSWORD=admin
      - APP_ENV=dev
      - APP_SECRET=13bf30003133e6c57953c89d7e0b72e9
      - KEYCLOAK_URL=http://matthieu.ga:2099/auth/realms/imt-mines-ales/protocol/openid-connect/userinfo
      - KEYCLOAK_CLIENT=gesco
      - KEYCLOAK_SECRET=f6XT5llLANFDQ7wpG8A23w8adb_U1pvvPaXwXE-EvNc
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: https://corentin-grard:DU1sMNVe9xssxyeKjYsY@gitlab.mines-ales.fr/infres-11-projet-3a/gesco/frontend.git
      args:
        - VUE_APP_KEYCLOAK_URL=http://matthieu.ga:2099/auth/
        - VUE_APP_KEYCLOAK_REALM=imt-mines-ales
        - VUE_APP_KEYCLOAK_CLIENT_ID=gesco
        - VUE_APP_BASE_URL=/
        - VUE_APP_BACKEND_BASE_URL=http://localhost:8000
    ports:
      - "8080:80"
