version: '3'

services:
  postgres:
      image: postgres
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
      image: jboss/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # KEYCLOAK_IMPORT: /tmp/realm-export.json
        JDBC_PARAMS: "ssl=false"
      ports:
        - "8090:8080"
      # volumes:
      #   - ./realm-export.json:/tmp/realm-export.json
      depends_on:
        - postgres

# volumes:
#   postgres_data: